language: python
# command to install dependencies
#install:
#  - pip install . --use-mirrors
#  - pip install -r requirements.txt --use-mirrors

install:
  - python setup.py install
script:
  - python setup.py test
